apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic
  namespace: ecmwf
spec:
  version: 7.7.0
  count: 1
  elasticsearchRef:
    name: elastic
    namespace: ecmwf
  http:
    service:
      spec:
        # expose this cluster Service with a LoadBalancer
        type: ClusterIP
        externalIPs: ['116.202.55.227']
