---
micronaut:
  application:
    name: cva-df-fullfillment
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:public"
---
#graphql:
#  graphiql.enabled: true
