name: ECMWF-virtual-assistant-documentation
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:

      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 13'
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: 'Check Java Version'
        run: |
          java --version
#      - name: 'Run asciidoctorPdf task'
#        run: |
#          ./gradlew asciidoctorPdf
#      - name: 'Publish documentation PDF'
#        if: always()
#        uses: actions/upload-artifact@v2-preview
#        with:
#          name: 'ECMWF-Conversational-Virtual-Assistant-documentation.pdf'
#          path: build/docs/asciidocPdf/ECMWF-Conversational-Virtual-Assistant.pdf
