name: ECMWF-virtual-assistant
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:

      - name: 'Start build job'
        run: |
          echo "Starting the build job."
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 13'
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Run cva-retrieval-pipeline Tests'
        run: |
          ./gradlew cva-retrieval-pipeline:test
      - name: 'Publish cva-retrieval-pipeline Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'cva-retrieval-pipeline-test-report'
          path: cva-retrieval-pipeline/build/reports/tests/test/*
